/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface VehicleConditionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getMyLevel"
      | "getMyScore"
      | "submitAndCompute"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyLevel",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitAndCompute",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMyLevel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMyScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitAndCompute",
    data: BytesLike
  ): Result;
}

export interface VehicleCondition extends BaseContract {
  connect(runner?: ContractRunner | null): VehicleCondition;
  waitForDeployment(): Promise<this>;

  interface: VehicleConditionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getMyLevel: TypedContractMethod<[], [string], "view">;

  getMyScore: TypedContractMethod<[], [string], "view">;

  submitAndCompute: TypedContractMethod<
    [
      cipherMileage: BytesLike,
      cipherAccidents: BytesLike,
      cipherSeverity: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMyLevel"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyScore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitAndCompute"
  ): TypedContractMethod<
    [
      cipherMileage: BytesLike,
      cipherAccidents: BytesLike,
      cipherSeverity: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
